{% set name = "nr.stream" %}
{% set version = "0.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nr.stream-{{ version }}.tar.gz
  sha256: 8b6949d768d2a54ddad5f9efa0f0eabb3c1b4e4a657aa2a0e70c0dc54aea527b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5,<4.0
  run:
    - nr.pylang.utils >=0.1.0,<1.0.0
    - python >=3.5,<4.0

test:
  imports:
    - nr
    - nr.stream
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://git.niklasrosenstein.com/NiklasRosenstein/nr
  summary: Use iterators like Java streams.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - NiklasRosenstein
